// <auto-generated />
namespace AppDev_MCA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateTraineeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTraineeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102010901330_updateTraineeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
